// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
	if (a0 == 0xc || a0 == 0xb) {
		char buf[128];
		sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1, (uint8_t)a2);
		return open(buf, O_RDWR, 0);
	} else {
		char buf[1024];
		char* hash;
strncpy(buf, (char*)a0, sizeof(buf) - 1);
		buf[sizeof(buf) - 1] = 0;
		while ((hash = strchr(buf, '#'))) {
			*hash = '0' + (char)(a1 % 10);
			a1 /= 10;
		}
		return open(buf, a2, 0);
	}
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 3ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20001ec0, "/dev/sg#\000", 9);
	res = syz_open_dev(0x20001ec0, 0, 2);
	if (res != -1)
		r[0] = res;
	syscall(__NR_read, r[0], 0x20001f00ul, 0x32ul);
*(uint16_t*)0x20001fc0 = 0x108;
*(uint8_t*)0x20001fc2 = 0x20;
*(uint8_t*)0x20001fc3 = 0;
*(uint32_t*)0x20001fc4 = 0x1c9;
*(uint32_t*)0x20001fc8 = 0x1ec;
*(uint32_t*)0x20001fcc = 9;
*(uint32_t*)0x20001fd0 = 0x141;
*(uint32_t*)0x20001fd4 = 7;
*(uint32_t*)0x20001fd8 = 0;
*(uint32_t*)0x20001fdc = 0;
*(uint64_t*)0x20001fe0 = 0;
*(uint64_t*)0x20001fe8 = 0;
*(uint64_t*)0x20001ff0 = 0;
*(uint64_t*)0x20001ff8 = 0;
*(uint64_t*)0x20002000 = 0;
*(uint64_t*)0x20002008 = 0;
*(uint64_t*)0x20002010 = 0;
*(uint64_t*)0x20002018 = 0;
*(uint64_t*)0x20002020 = 0;
*(uint64_t*)0x20002028 = 0;
*(uint64_t*)0x20002030 = 0;
*(uint64_t*)0x20002038 = 0;
*(uint64_t*)0x20002040 = 0;
*(uint64_t*)0x20002048 = 0;
*(uint64_t*)0x20002050 = 0;
*(uint64_t*)0x20002058 = 0;
*(uint64_t*)0x20002060 = 0;
*(uint64_t*)0x20002068 = 0;
*(uint64_t*)0x20002070 = 0;
*(uint64_t*)0x20002078 = 0;
*(uint64_t*)0x20002080 = 0;
*(uint64_t*)0x20002088 = 0;
*(uint64_t*)0x20002090 = 0;
*(uint64_t*)0x20002098 = 0;
*(uint64_t*)0x200020a0 = 0;
*(uint64_t*)0x200020a8 = 0;
*(uint64_t*)0x200020b0 = 0;
*(uint64_t*)0x200020b8 = 0;
*(uint64_t*)0x200020c0 = 0;
*(uint64_t*)0x200020c8 = 0;
*(uint64_t*)0x200020d0 = 0;
*(uint64_t*)0x200020d8 = 0;
*(uint64_t*)0x200020e0 = 0;
*(uint64_t*)0x200020e8 = 0;
*(uint64_t*)0x200020f0 = 0;
*(uint64_t*)0x200020f8 = 0;
*(uint64_t*)0x20002100 = 0;
*(uint64_t*)0x20002108 = 0;
*(uint64_t*)0x20002110 = 0;
*(uint64_t*)0x20002118 = 0;
*(uint64_t*)0x20002120 = 0;
*(uint64_t*)0x20002128 = 0;
*(uint64_t*)0x20002130 = 0;
*(uint64_t*)0x20002138 = 0;
*(uint64_t*)0x20002140 = 0;
*(uint64_t*)0x20002148 = 0;
*(uint64_t*)0x20002150 = 0;
*(uint64_t*)0x20002158 = 0;
*(uint64_t*)0x20002160 = 0;
*(uint64_t*)0x20002168 = 0;
*(uint64_t*)0x20002170 = 0;
*(uint64_t*)0x20002178 = 0;
*(uint64_t*)0x20002180 = 0;
*(uint64_t*)0x20002188 = 0;
*(uint64_t*)0x20002190 = 0;
*(uint64_t*)0x20002198 = 0;
*(uint64_t*)0x200021a0 = 0;
*(uint64_t*)0x200021a8 = 0;
*(uint64_t*)0x200021b0 = 0;
*(uint64_t*)0x200021b8 = 0;
*(uint64_t*)0x200021c0 = 0;
*(uint64_t*)0x200021c8 = 0;
*(uint64_t*)0x200021d0 = 0;
*(uint64_t*)0x200021d8 = 0;
*(uint64_t*)0x200021e0 = 0;
*(uint64_t*)0x200021e8 = 0;
*(uint64_t*)0x200021f0 = 0;
*(uint64_t*)0x200021f8 = 0;
*(uint64_t*)0x20002200 = 0;
*(uint64_t*)0x20002208 = 0;
*(uint64_t*)0x20002210 = 0;
*(uint64_t*)0x20002218 = 0;
*(uint64_t*)0x20002220 = 0;
*(uint64_t*)0x20002228 = 0;
*(uint64_t*)0x20002230 = 0;
*(uint64_t*)0x20002238 = 0;
*(uint64_t*)0x20002240 = 0;
*(uint64_t*)0x20002248 = 0;
*(uint64_t*)0x20002250 = 0;
*(uint64_t*)0x20002258 = 0;
*(uint64_t*)0x20002260 = 0;
*(uint64_t*)0x20002268 = 0;
*(uint64_t*)0x20002270 = 0;
*(uint64_t*)0x20002278 = 0;
*(uint64_t*)0x20002280 = 0;
*(uint64_t*)0x20002288 = 0;
*(uint64_t*)0x20002290 = 0;
*(uint64_t*)0x20002298 = 0;
*(uint64_t*)0x200022a0 = 0;
*(uint64_t*)0x200022a8 = 0;
*(uint64_t*)0x200022b0 = 0;
*(uint64_t*)0x200022b8 = 0;
*(uint64_t*)0x200022c0 = 0;
*(uint64_t*)0x200022c8 = 0;
*(uint64_t*)0x200022d0 = 0;
*(uint64_t*)0x200022d8 = 0;
*(uint64_t*)0x200022e0 = 0;
*(uint64_t*)0x200022e8 = 0;
*(uint64_t*)0x200022f0 = 0;
*(uint64_t*)0x200022f8 = 0;
*(uint64_t*)0x20002300 = 0;
*(uint64_t*)0x20002308 = 0;
*(uint64_t*)0x20002310 = 0;
*(uint64_t*)0x20002318 = 0;
*(uint64_t*)0x20002320 = 0;
*(uint64_t*)0x20002328 = 0;
*(uint64_t*)0x20002330 = 0;
*(uint64_t*)0x20002338 = 0;
*(uint64_t*)0x20002340 = 0;
*(uint64_t*)0x20002348 = 0;
*(uint64_t*)0x20002350 = 0;
*(uint64_t*)0x20002358 = 0;
*(uint64_t*)0x20002360 = 0;
*(uint64_t*)0x20002368 = 0;
*(uint64_t*)0x20002370 = 0;
*(uint64_t*)0x20002378 = 0;
*(uint64_t*)0x20002380 = 0;
*(uint64_t*)0x20002388 = 0;
*(uint64_t*)0x20002390 = 0;
*(uint64_t*)0x20002398 = 0;
*(uint64_t*)0x200023a0 = 0;
*(uint64_t*)0x200023a8 = 0;
*(uint64_t*)0x200023b0 = 0;
*(uint64_t*)0x200023b8 = 0;
*(uint64_t*)0x200023c0 = 0;
*(uint64_t*)0x200023c8 = 0;
*(uint64_t*)0x200023d0 = 0;
*(uint64_t*)0x200023d8 = 0;
	syscall(__NR_write, r[0], 0x20001fc0ul, 0x420ul);
	return 0;
}
