// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[3] = {0x0, 0x0, 0x0};

int main(void)
{
		syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 3ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
memcpy((void*)0x20000000, "user\000", 5);
memcpy((void*)0x20000040, "syz", 3);
*(uint8_t*)0x20000043 = 0x21;
*(uint8_t*)0x20000044 = 0;
memcpy((void*)0x20000080, "\x86", 1);
	res = syscall(__NR_add_key, 0x20000000ul, 0x20000040ul, 0x20000080ul, 1ul, -1);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x20000000, "keyring\000", 8);
memcpy((void*)0x20000040, "syz", 3);
*(uint8_t*)0x20000043 = 0x22;
*(uint8_t*)0x20000044 = 0;
	res = syscall(__NR_add_key, 0x20000000ul, 0x20000040ul, 0ul, 0ul, 0xfffffffc);
	if (res != -1)
		r[1] = res;
	syscall(__NR_keyctl, 0xbul, r[0], 0x200001c0ul, 0xdful, 0);
memcpy((void*)0x20000140, "syzkaller\000", 10);
memcpy((void*)0x20000180, "syz", 3);
*(uint8_t*)0x20000183 = 0x23;
*(uint8_t*)0x20000184 = 0;
	syscall(__NR_keyctl, 0xaul, r[0], 0x20000140ul, 0x20000180ul, r[1]);
memcpy((void*)0x20000000, "keyring\000", 8);
memcpy((void*)0x20000040, "syz", 3);
*(uint8_t*)0x20000043 = 0x22;
*(uint8_t*)0x20000044 = 0;
	res = syscall(__NR_add_key, 0x20000000ul, 0x20000040ul, 0ul, 0ul, 0xfffffffc);
	if (res != -1)
		r[2] = res;
	syscall(__NR_keyctl, 0xbul, r[2], 0x20000280ul, 0x5dul, 0);
	syscall(__NR_keyctl, 0x15ul, r[2], 0, 0, 0);
	return 0;
}
