// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 3ul, 0x32ul, -1, 0ul);
				intptr_t res = 0;
	syscall(__NR_socket, 2ul, 1ul, 0);
	res = syscall(__NR_socket, 2ul, 1ul, 0);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x200000c0, "\xbf\x43\x4c\x57\x79\xd6\x95\x39\x26\x38\x7f\x47\x0d\xef\x1e\x85", 16);
	syscall(__NR_setsockopt, r[0], 6, 0x21, 0x200000c0ul, 0x10ul);
*(uint32_t*)0x20000040 = 0x1b;
	syscall(__NR_getsockopt, r[0], 6, 0x21, 0x20000000ul, 0x20000040ul);
	return 0;
}
